apiVersion: v1
kind: Secret
metadata:
  name: valve-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLW5tITVvJnMtOXoqbj01dyZAcTdjKGstMEBmJTYzIyApQGo1ZShsQHcjZCMqb18z
